// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabajo_Practico.Data;

#nullable disable

namespace Trabajo_Practico.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20261006230104_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trabajo_Practico.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Remeras de algodón Remeras musculosas Bodys manga corta",
                            Nombre = "Remeras"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Sastreros del 36 al 46 Jeans Mom 36 al 46 Jeans Oxford 36 al 46 Calzas 36 al 46",
                            Nombre = "Pantalones (mujer)"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Buzos Básicos 1 al 6 Buzos Oversize (Talle Único) Buzos Cortos (Talle Único)",
                            Nombre = "Buzos"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Minis Shorts 36 al 42 Shorts básicos 36 al 46 Polleras mini (talle 1 al 3)",
                            Nombre = "Shorts, polleras de mujer"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Descripcion = "Conjunto deportivo de Argentina(solo disponible talle 1 y 2)",
                            Nombre = "Ropa deportiva"
                        });
                });

            modelBuilder.Entity("Trabajo_Practico.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Talle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Color = "Blanco",
                            Descripcion = "Remera de algodón lisa",
                            Nombre = "Remera básica",
                            Precio = 15000m,
                            Stock = 10,
                            Talle = "M"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 2,
                            Color = "Celeste",
                            Descripcion = "Jean de tiro alto",
                            Nombre = "Jean Mom",
                            Precio = 42000m,
                            Stock = 5,
                            Talle = "38"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 3,
                            Color = "Rosa",
                            Descripcion = "Buzo con capucha",
                            Nombre = "Buzo oversize",
                            Precio = 38000m,
                            Stock = 0,
                            Talle = "Único"
                        });
                });

            modelBuilder.Entity("Trabajo_Practico.Models.Producto", b =>
                {
                    b.HasOne("Trabajo_Practico.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
